import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { Command } from "commander";

import { die, header, info, success, table, warn } from "../lib/output.js";

/**
 * `canopy release` — scaffold a dApp Store submission config
 *
 * Generates a `dapp-store.yaml` file in the current directory that can be
 * passed to `@solana-mobile/dapp-store-cli` for submission.
 *
 * NOTE: dApp Store Portal API endpoints are not yet confirmed — this command
 * generates a local config file that the publisher submits manually or via
 * the @solana-mobile/dapp-store-cli publish command.
 */
export function registerReleaseCommand(program: Command): void {
    const cmd = program
        .command("release")
        .description("prepare a dApp Store submission config");

    cmd
        .command("init")
        .description(
            "generate a dapp-store.yaml submission template in the current directory",
        )
        .option("--app <appId>", "app UUID from the Canopy dashboard")
        .option("--track <trackId>", "beta track ID to promote to production")
        .option("--out <dir>", "output directory", ".")
        .action(
            (opts: {
                app?: string;
                track?: string;
                out: string;
            }) => {
                if (!existsSync(opts.out)) {
                    mkdirSync(opts.out, { recursive: true });
                }

                const outPath = join(opts.out, "dapp-store.yaml");
                if (existsSync(outPath)) {
                    die(
                        `${outPath} already exists. Delete it first or choose a different --out directory.`,
                    );
                }

                const yaml = buildYamlTemplate(opts.app, opts.track);
                writeFileSync(outPath, yaml, "utf-8");

                success(`Created ${outPath}`);
                header("Next Steps");
                table(
                    [
                        [
                            "1. Edit",
                            `${outPath} — fill in all required fields`,
                        ],
                        [
                            "2. Install",
                            "npm install -g @solana-mobile/dapp-store-cli",
                        ],
                        [
                            "3. Submit",
                            "dapp-store publish submit --config dapp-store.yaml",
                        ],
                    ],
                    4,
                );
                console.log();
                warn(
                    "dApp Store Portal API endpoints require research — see docs/ROADMAP.md for current status.",
                );
            },
        );

    cmd
        .command("validate")
        .description("validate an existing dapp-store.yaml")
        .option("--config <path>", "path to config file", "dapp-store.yaml")
        .action((opts: { config: string }) => {
            if (!existsSync(opts.config)) {
                die(`Config file not found: ${opts.config}`);
            }
            info(
                "Validation via @solana-mobile/dapp-store-cli — running check…",
            );
            // NOTE: dapp-store validate is not yet confirmed in the @solana-mobile/dapp-store-cli API.
            // This requires research during implementation against the actual CLI schema.
            warn(
                "Full dApp Store schema validation requires @solana-mobile/dapp-publishing v0.13.0+.",
            );
            info(
                "Run: npx @solana-mobile/dapp-store-cli validate --config " +
                opts.config,
            );
        });
}

function buildYamlTemplate(appId?: string, trackId?: string): string {
    return `# Canopy — dApp Store submission config
# Generated by: canopy release init
#
# Fill in all required fields marked with <REQUIRED>.
# Submit using @solana-mobile/dapp-store-cli v0.13.0+
# Docs: https://docs.solanamobile.com/dapp-publishing/intro
#
# NOTE: dApp Store Portal API integration is pending research.
# See docs/ROADMAP.md for the current implementation status.

publisher:
  # Your publisher wallet address (the one used to sign SIWS on Canopy)
  wallet: <REQUIRED>

app:
  # App UUID from the Canopy dashboard${appId ? "\n  canopy_app_id: " + appId : "\n  canopy_app_id: <REQUIRED>"}
  # Your app's NFT mint address on the dApp Store
  # This is created on first publish via dapp-store-cli
  mint_address: <REQUIRED_AFTER_FIRST_PUBLISH>

release:
  # The beta track to promote to production${trackId ? "\n  canopy_track_id: " + trackId : ""}
  version: <REQUIRED>             # e.g. 1.0.0
  version_code: <REQUIRED>        # integer, must match APK
  release_date: <REQUIRED>        # ISO 8601, e.g. 2025-01-01

  apk:
    # Path to the signed APK (relative to this file)
    path: <REQUIRED>              # e.g. ./build/release/app-release.apk
    # SHA-256 hash of the APK for integrity verification
    sha256: <REQUIRED>

  # Localised store listing
  catalog:
    en:
      short_description: <REQUIRED>   # ≤ 80 chars
      long_description: <REQUIRED>    # ≤ 4000 chars
      # Paths to marketing assets
      icon: <REQUIRED>                # 512×512 PNG
      feature_graphic: <REQUIRED>     # 1024×500 PNG
      screenshots:
        - <REQUIRED>                  # at least one 1080×1920 PNG
`;
}
